ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image = "waldvogel/vagrant-chef-puppet:ubuntu-12.04"
    d.has_ssh = true
  end
end
